[package]
name = "csgo-server-terminal-app"
version = "0.5.1"
edition = "2021"
keywords = ["csgo", "dedicated", "server"]
authors = ["NFSS10"]
description = "A simple application to setup and run a Counter-Strike: Global Offensive dedicated server"
license = "Apache-2.0"
homepage = "https://github.com/NFSS10/csgo-server"
repository = "https://github.com/NFSS10/csgo-server"
readme = "README.md"

[dependencies]
csgo_server_lib = { path = "../lib" }
menu_rs = "0.2.2"


[profile.dev]
opt-level = 0

[profile.release]
debug = false
opt-level = 3
